@startuml
'https://plantuml.com/component-diagram

node "K8S" {
    [Nginx/Ingress]

    node "Old App" {
        [PHP-fpm]
    }

    node "Go Webserver" {
      [Go]
    }

}

[Nginx/Ingress] --> [Go]
[Go] --> [PHP-fpm] : Using fast-cgi library

@enduml